name: KitBox
version: 0.5
description: Kits without commands with using personality box (inventory in any block).
author: Jamefrus
website: https://vk.com/jfdev
main: su.jfdev.cubes.plugins.kitbox.Main
commands:
  kitbox:
    description: /kitbox help to more
    aliases: [kb,setbox]
  kbreload:
    description: Mirror for /kitbox reload
  kbhelp:
    description: Mirror for /kitbox help
  kbcreate:
    description: Mirror for /kitbox create
  kbsave:
    description: Mirror for /kitbox save
  kbremove:
    description: Mirror for /kitbox remove
  kbreown:
    description: Mirror for /kitbox setowner
  kbrename:
    description: Mirror for /kitbox setname
  kbresize:
    description: Mirror for /kitbox setsize